# Generated by Django 4.2.4 on 2023-08-13 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ATM',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ATM_location', models.CharField(choices=[('Alexander City', 'Alexander City'), ('Andalusia', 'Andalusia'), ('Anniston', 'Anniston'), ('Athens', 'Athens'), ('Atmore', 'Atmore')], default='location', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(default='', max_length=100)),
                ('name', models.CharField(default='', max_length=100)),
                ('amount', models.IntegerField(default=0)),
                ('account_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerSignIn',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_date', models.DateTimeField()),
                ('transaction_amount', models.FloatField()),
                ('transaction_status', models.CharField(max_length=50)),
                ('completed', models.BooleanField(default=True)),
                ('atm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.atm')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.customers')),
            ],
        ),
    ]
