# Generated by Django 4.2.1 on 2023-08-21 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='customer_cpr',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='customers',
            name='pin_code',
            field=models.CharField(default='', max_length=4),
        ),
    ]
